spring.application.name=ems-backend
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

